image: Ubuntu

version: "{build}"

branches:
  only:
    - master

build: off

install:
  - bundle install

environment:
  matrix:
    - RUBY_VERSION: 21
    - RUBY_VERSION: 22
    - RUBY_VERSION: 23
    - RUBY_VERSION: 24
    - RUBY_VERSION: 25

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - chmod +x ./scripts/cibuild

test_script:
  - ./scripts/cibuild

cache: bundler
