# General
title: Staticaly
tagline: Free CDN for Everyone! Load Project from GitHub, GitLab and Bitbucket more easier #Make it Static!
description: Staticaly is Free, Open Source CDN Library with Advanced features so you can load your project more easier.
logo: /static/images/staticaly_icon.png
lang: en_US
url: https://www.staticaly.com
encoding: UTF-8
permalink: /:title
highlighter: rouge
env: production
version: 0.1
year: 2018

# Utilities
future: true
jailed: false
gfm_quirks: paragraph_end

# Staticaly
staticaly:
    blog_url: https://blog.staticaly.com
    devs_url: https://developers.staticaly.com
    datacenter_num: 152
    newsletter_url: https://marsble.us18.list-manage.com/subscribe/post?u=4dfd4ae04677bf4f6248182fc&amp;id=397ea962f2

# Analytics
marsble:
    username: staticaly
    analytics_url: https://pixel.marsble.com
    analytics_id: 921b301945cfd2a048e13a9d1a1b67a86be4b8c8

# Google
google:
    analytics_id: UA-74801412-7

# Social
social:
    name: Staticaly
    links:
      - https://www.marsble.com/user/staticaly
      - https://twitter.com/staticalycom
      - https://www.instagram.com/staticalycom
      - https://www.facebook.com/staticaly
      - https://www.linkedin.com/company/staticaly
      - https://plus.google.com/+staticaly
      - https://github.com/staticaly

# Twitter
twitter:
    username: staticalycom

# Facebook
facebook:
    app_id: 1234
    publisher: staticaly
    admins: fransallen

# Instagram
instagram:
    username: staticalycom

# GitHub
github_username: staticaly

# The author
author:
    twitter: fransallen

# Default image for socmed
defaults:
  - scope:
      path: ''
    values:
      image: /static/images/staticaly_icon_bg_dark_lg.png

# Static files
cdn:
    domain: cdn.staticaly.com
    url: https://cdn.staticaly.com
    imgpx_domain: img.staticaly.com
    imgpx_url: https://img.staticaly.com
    favicons_domain: favicons.staticaly.com
    favicons_url: https://favicons.staticaly.com
    static_url: https://static.marsble.com
sass:
    sass_dir: ./static/css
    style: compressed

include:
    - '_pages'
    - '_redirections'

kramdown:
    input: GFM
    hard_wrap: false

# Plugins
plugins:
    - jekyll-coffeescript
    - jekyll-seo-tag
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-minifier
